export const CHART_KEYS = {
  // Embedded / legacy
  PRIMARY: "PRIMARY",

  // Held grid
  GRID_1: "GRID_1",
  GRID_2: "GRID_2",
  GRID_3: "GRID_3",
  GRID_4: "GRID_4",
  GRID_5: "GRID_5",
  GRID_6: "GRID_6",

  // Watchlist composites
  WATCHLIST_LAUNCH: "WATCHLIST_LAUNCH",
  WATCHLIST_HVM: "WATCHLIST_HVM",
  WATCHLIST_SLOW: "WATCHLIST_SLOW",

  // Analysis grid tiles (dedicated, avoids MODAL_* collisions)
  ANALYSIS_GRID_1: "ANALYSIS_GRID_1",
  ANALYSIS_GRID_2: "ANALYSIS_GRID_2",
  ANALYSIS_GRID_3: "ANALYSIS_GRID_3",
  ANALYSIS_GRID_4: "ANALYSIS_GRID_4",
  ANALYSIS_GRID_5: "ANALYSIS_GRID_5",
  ANALYSIS_GRID_6: "ANALYSIS_GRID_6",
  ANALYSIS_GRID_7: "ANALYSIS_GRID_7",
  ANALYSIS_GRID_8: "ANALYSIS_GRID_8",
  ANALYSIS_GRID_9: "ANALYSIS_GRID_9",

  // Modal charts (ad-hoc)
  MODAL_1: "MODAL_1",
  MODAL_2: "MODAL_2",
  MODAL_3: "MODAL_3",
  MODAL_4: "MODAL_4",
  MODAL_5: "MODAL_5",
  MODAL_6: "MODAL_6",
  MODAL_7: "MODAL_7",
  MODAL_8: "MODAL_8",
  MODAL_9: "MODAL_9",
  MODAL_10: "MODAL_10",
  MODAL_11: "MODAL_11",
  MODAL_12: "MODAL_12",
  MODAL_13: "MODAL_13",
  MODAL_14: "MODAL_14",
  MODAL_15: "MODAL_15",
  MODAL_16: "MODAL_16",
  MODAL_17: "MODAL_17",
  MODAL_18: "MODAL_18",
  MODAL_19: "MODAL_19",
  MODAL_20: "MODAL_20",
  MODAL_21: "MODAL_21",
  MODAL_22: "MODAL_22",
  MODAL_23: "MODAL_23",
  MODAL_24: "MODAL_24",
} as const;

export type ChartKey = (typeof CHART_KEYS)[keyof typeof CHART_KEYS];